name: ci

on:
  pull_request:
  push:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run fmt:check
